### ISSUE TITLE
Exception: cannot add a duplicate edge

### ISSUE THREAD

**Issue by alecava58** [itinero/idp#11]
Hi all,
Creating a router db (Italy) using IDP I got the following exception (see picture).
I tried with pre-37 and the latest pre-62 version of Itinero.

Is there something that I can do?

![image](https://user-images.githubusercontent.com/1788993/41835859-49dbab32-7859-11e8-8163-8f4d3e8c0aef.png)

**Comment by xivk** [comment]
Fixed in Itinero.
