### ISSUE TITLE
[Question] Filtering

### ISSUE THREAD

**Issue by juliusfriedman** [itinero/idp#17]
Is there any option to filter with idp? It seems like all the other pieces are in place to allow idp to select by bounding box and or feature similar to osmium.

Is there any example of this or is it simply not possible [yet]?

**Comment by xivk** [comment]
It's not really the goal of IDP to provide that but it could. There are some piece of that code here:

https://github.com/itinero/idp/tree/develop/src/IDP/Switches
https://github.com/OsmSharp/odp/blob/develop/OsmSharpDataProcessor/Commands/CommandFilterBoundingBox.cs

But that hasn't been ported here. Basically filtering is usually done with another tool, like osmium before giving it to IDP.

**Comment by juliusfriedman** [comment]
Thought so, thank you!
