### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by jbelien** [itinero/idp#7]
Would it be possible to add Debian 9 build ?

I tried to update `IDP.csproj` with the following but it didn't work.
```
<RuntimeIdentifiers>win8-x64;win10-x64;osx.10.11-x64;ubuntu.16.04-x64;debian-x64</RuntimeIdentifiers>
```
and
```
<RuntimeIdentifiers>win8-x64;win10-x64;osx.10.11-x64;ubuntu.16.04-x64;debian.9-x64</RuntimeIdentifiers>
```

Then run `dotnet publish -c release -r debian-x64` and `dotnet publish -c release -r debian.9-x64` but it didn't generate the `./IDP` executable.
I guess I missed something !

Thanks :)

**Comment by xivk** [comment]
This is not needed anymore, you can just define the platform during build as you did already here:

`dotnet publish -c release -r debian.9-x64`

You don't even need them in the project file. It should also be fine to use:

`dotnet publish -c release -r linux-x64`

That should work on most linux flavours. Feel free to reopen if this isn't working or you still have issues.
